wrtc-lt: More improvements and features for load test (#347)
* wrtc-lt/orch: Delete jobs in parallel for quick cleanup

* wrtc-lt/orch: Allow specifying an existing stream id

* wrtc-lt: Allow testing access controlled streams

* wrtc-lt/orch: Remove webrtc- prefix from job names

* .github: Add new params to github action

* .github: nits

* .github: Improve discord messages a bit

* [DEV-ONLY] Use pending container image

* .github: Fail early if access control is set without single-node

* wrtc-lt: Fix public key derivation

* wrtc-lt: Remove webrtc- prefix from job names

* .github: Replace stream-id with custom args

* .github: Remove explicit stream-id input

* Revert "[DEV-ONLY] Use pending container image"

This reverts commit b4413cbe22e383be99a284dab3ff89697859914f.

diff --git a/.github/workflows/load-test.yaml b/.github/workflows/load-test.yaml
--- a/.github/workflows/load-test.yaml
+++ b/.github/workflows/load-test.yaml
@@ -16,12 +16,23 @@ on:
         type: string
         default: 5m
       streamer-region:
-        description: Google Cloud region to stream from
+        description: Streamer region (from Google Cloud)
         type: string
         required: true
         default: us-central1
+      playback-protocol:
+        description: Playback protocol
+        required: true
+        type: choice
+        options: [ "WebRTC", "HLS" ]
+        default: "WebRTC"
+      access-control:
+        description: Enable JWT access control
+        type: boolean
+        required: true
+        default: false
       playback-region-viewers-json:
-        description: Map of Google Cloud region to desired number of viewers
+        description: Number of viewers per region (from Google Cloud)
         type: string
         required: true
         default: '{"us-central1":20,"europe-west2":20,"asia-southeast1":20}'
@@ -30,12 +41,6 @@ on:
         type: string
         required: true
         default: 'https://storage.googleapis.com/lp_testharness_assets/countdown_720p_30fps_2sGOP_noBframes_5min.mp4'
-      playback-protocol:
-        description: Playback protocol
-        required: true
-        type: choice
-        options: [ "WebRTC", "HLS" ]
-        default: "WebRTC"
       region:
         description: "(Optional) Single-node test: Region of node to be tested (also needs pod index below). e.g.: mdw"
         type: string
@@ -44,7 +49,11 @@ on:
         description: "(Optional) Single-node test: Index of the Catalyst pod to be tested (also needs region above). e.g.: 0"
         type: string
         required: false
-        default: ''
+      extra-args:
+        description:
+          (Optional) Additional arguments to send to load test orchestrator
+        type: string
+        required: false
 jobs:
   load-test:
     name: Run ${{ inputs.playback-protocol }} load test
@@ -66,7 +75,7 @@ jobs:
           DISCORD_EMBEDS: >
             [{
               "title": "${{ inputs.playback-protocol }} load test starting",
-              "description": "A load test is starting (env=${{ inputs.environment }})",
+              "description": "A load test is starting in **${{ inputs.environment }}**",
               "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "timestamp": "${{ steps.timestamp.outputs.date }}",
               "author": {
@@ -98,6 +107,10 @@ jobs:
                 "name": "Single-node target",
                 "value": "${{ inputs.region }}-${{ inputs.pod-index }}",
                 "inline": true
+              }, {
+                "name": "Access control",
+                "value": "${{ inputs.access-control }}",
+                "inline": true
               }]
             }]
 
@@ -110,11 +123,27 @@ jobs:
               API_TOKEN="${{ secrets.LOAD_TEST_PROD_API_KEY }}"
               STREAMER_BASE_URL="rtmp://rtmp.livepeer.com/live/"
               PLAYBACK_BASE_URL="https://lvpr.tv/"
+
+              if [ "${{ inputs.access-control }}" = "true" ]; then
+                  if [ -z "${{ inputs.region }}" ] && [ -z "${{ inputs.pod-index }}" ]; then
+                      echo "Error: access-control is only available for single node tests"
+                      exit 1
+                  fi
+                  PLAYBACK_JWT_PRIVATE_KEY="${{ secrets.LOAD_TEST_PROD_JWT_PRIVATE_KEY }}"
+              fi
           else
               API_SERVER="livepeer.monster"
               API_TOKEN="${{ secrets.LOAD_TEST_STAGING_API_KEY }}"
               STREAMER_BASE_URL="rtmp://rtmp.livepeer.monster/live/"
               PLAYBACK_BASE_URL="https://monster.lvpr.tv/"
+
+              if [ "${{ inputs.access-control }}" = "true" ]; then
+                  if [ -z "${{ inputs.region }}" ] && [ -z "${{ inputs.pod-index }}" ]; then
+                      echo "Error: access-control is only available for single node tests"
+                      exit 1
+                  fi
+                  PLAYBACK_JWT_PRIVATE_KEY="${{ secrets.LOAD_TEST_STAGING_JWT_PRIVATE_KEY }}"
+              fi
           fi
 
           # Override with inputs
@@ -142,9 +171,10 @@ jobs:
           echo "::set-output name=streamer-base-url::${STREAMER_BASE_URL}"
           echo "::set-output name=playback-base-url::${PLAYBACK_BASE_URL}"
           echo "::set-output name=playback-manifest-url::${PLAYBACK_MANIFEST_URL}"
+          echo "::set-output name=playback-jwt-private-key::${PLAYBACK_JWT_PRIVATE_KEY}"
 
       - name: Load Test
-        run: webrtc-load-tester orchestrator
+        run: webrtc-load-tester orchestrator ${{ inputs.extra-args }}
         env:
           LT_WEBRTC_DURATION: ${{ inputs.duration }}
           LT_WEBRTC_API_SERVER: ${{ steps.env.outputs.api-server }}
@@ -154,6 +184,7 @@ jobs:
           LT_WEBRTC_STREAMER_INPUT_FILE: ${{ inputs.streamer-input-file }}
           LT_WEBRTC_PLAYBACK_BASE_URL: ${{ steps.env.outputs.playback-base-url }}
           LT_WEBRTC_PLAYBACK_MANIFEST_URL: "${{ steps.env.outputs.playback-manifest-url }}"
+          LT_WEBRTC_PLAYBACK_JWT_PRIVATE_KEY: ${{ steps.env.outputs.playback-jwt-private-key }}
           LT_WEBRTC_PLAYBACK_VIEWERS_PER_WORKER: 10
           LT_WEBRTC_PLAYBACK_VIEWERS_PER_CPU: 2
           LT_WEBRTC_PLAYBACK_MEMORY_PER_VIEWER_MIB: 400
@@ -169,7 +200,7 @@ jobs:
           DISCORD_EMBEDS: >
             [{
               "title": "${{ inputs.playback-protocol }} load test finished successfully",
-              "description": "The load test (env=${{ inputs.environment }}) has finished successfully",
+              "description": "The load test has finished successfully",
               "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "color": 24576,
               "author": {
@@ -196,7 +227,7 @@ jobs:
           DISCORD_USERNAME: ${{ github.triggering_actor }}
           DISCORD_EMBEDS: >
             [{
-              "title": "${{ inputs.playback-protocol }} load test has failed! (env=${{ inputs.environment }})",
+              "title": "${{ inputs.playback-protocol }} load test has failed!,
               "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "color": 8388608,
               "author": {
@@ -223,7 +254,7 @@ jobs:
           DISCORD_USERNAME: ${{ github.triggering_actor }}
           DISCORD_EMBEDS: >
             [{
-              "title": "${{ inputs.playback-protocol }} load test was cancelled! (env=${{ inputs.environment }})",
+              "title": "${{ inputs.playback-protocol }} load test was cancelled!",
               "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
               "color": 11778048,
               "author": {
